### PR TITLE
Additional Text Adding to the Code of Conduct

### PR DESCRIPTION
**Pull request by srpanoplos**
This seems like a partial code of conduct  - per the discussion on the recent Code of Conduct change, I am opening a separate pull request to have this standard language added:

 "in the interest of fostering an open and welcoming community, we pledge to respect all people who contribute through reporting issues, making comments, posting feature requests, updating documentation, submitting pull requests or patches, and other activities.."

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Jun 08, 2016 at 12:33:27PM -0700, srpanoplos wrote:
> I am opening a separate pull request to have this standard language added:
> 
> "in the interest of fostering an open and welcoming community, we
> pledge to respect all people who contribute through reporting
> issues, making comments, posting feature requests, updating
> documentation, submitting pull requests or patches, and other
> activities.."

  $ git log --graph --oneline --decorate origin/pr/13 | head -n5
  *   9361e90 (origin/pr/13, origin/image-format-proposal) Merge pull request #5 from philips/image-format-proposal
  |\  
  | * dffd27e (origin/pr/6, origin/pr/5) proposals: image-format: remove the distribution related goals
  |/  
  * 02a8bc0 (origin/pr/4) Add image format project proposal

You're only new commit is currently a merge of two already-landed PRs,
so it doesn't actually change master.  Do you have a commit adding
your suggested language you could push (probably dropping 9361e90 and
building off the current master)?

**Comment by caniszczyk** [comment]
@srpanoplos I believe this is handled here in the current language:

> We are committed to making participation in this project a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality.

Some of the code of conduct was based on an older version of the Contributor Covenant (http://contributor-covenant.org/) so I think that's why the language is in a bit of a differnent place.

**Comment by wking** [comment]
On Thu, Jun 09, 2016 at 09:06:05AM -0700, Chris Aniszczyk wrote:
> @srpanoplos I believe this is handled here in the current language:
> 
> > We are committed to making participation in this project a
> > harassment-free experience for everyone, regardless of level of
> > experience, gender, gender identity and expression, sexual
> > orientation, disability, personal appearance, body size, race,
> > ethnicity, age, religion, or nationality.

That has “harrassment-free” (which is sort of a backhanded positive),
followed by lots of attributes that are frequently used for
harrassment.  I think what @srpanoplos (and I agree) is looking for is
an entirely positive paragraph (“open”, “welcoming”, “respect”,
“please contribute”) that doesn't dip into potential negative
interactions (which are already forbidden by the current wording).

So “this is the environment we're trying to build” to balance the
current “these are not the environments we're trying to build”.

**Comment by caniszczyk** [comment]
@wking @srpanoplos would you be OK just updating to the latest http://contributor-covenant.org/version/1/4/ ? seems to solve our problem mostly

**Comment by wking** [comment]
On Thu, Jun 09, 2016 at 09:23:00AM -0700, Chris Aniszczyk wrote:
> would you be OK just updating to the latest
> http://contributor-covenant.org/version/1/4/ ?

Works for me, and they even have an enforcement section with a
placeholder for a reporting email (which looks very similar to the
language from #12).

**Comment by caniszczyk** [comment]
@wking @srpanoplos ok I filed the PR here:
https://github.com/opencontainers/tob/pull/14

We can close this one if the other one gets merged in.

Thanks! I'll also send a note out to the dev@opencontainers.org reminding folks about it!

**Comment by srpanoplos** [comment]
Thanks @wking and @caniszcsyk - can you clarify who makes up the project
team (i.e. where the email is sent as no URL is listed in #14)?



On Thu, Jun 9, 2016 at 9:55 AM, Chris Aniszczyk <notifications@github.com>
wrote:

> Closed #13 <https://github.com/opencontainers/tob/pull/13>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/opencontainers/tob/pull/13#event-687522163>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AMDEdyUBSIq71Y7YCz3wJOwzlT-e1YnVks5qKEVkgaJpZM4IxUX6>
> .
>



-- 
*Suzanne Panoplos*
*Director of Corporate Communications*
*Docker*


<http://2016.dockercon.com/?utm_source=signature&utm_medium=email&utm_campaign=bm>

**Comment by wking** [comment]
On Fri, Jun 10, 2016 at 02:38:03AM -0700, srpanoplos wrote:
> Thanks @wking and @caniszcsyk - can you clarify who makes up the
> project team (i.e. where the email is sent as no URL is listed in
> #14)?

There's still a violation-report email in #14 [1].  Are you looking
for a link to who will be reading the email?

[1]: https://github.com/opencontainers/tob/pull/14/files#diff-d3030a18b089fdb1fbfabf6e75e4aef0R57

**Pull request closed without merging**
